name: Lint
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Ls
        run: ls
      - name: Install eslint
        run: yarn install
      - name: Run ESLint
        run: yarn lint