name: Lint
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Update working dir
        run: cd ../
      - name: Install eslint
        run: yarn install
      - name: Run ESLint
        run: yarn lint